version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Europe/London
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    groups:
      production-major:
        dependency-type: production
        update-types:
          - major
      production-minor-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-major:
        dependency-type: development
        update-types:
          - major
      development-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:30'
      timezone: Europe/London
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - '*'
