/**
 * Database Type Helpers
 *
 * This file provides convenience type aliases for Supabase database operations.
 * It re-exports everything from the auto-generated database.ts file.
 *
 * IMPORTANT: Import from this file, not directly from database.ts
 * Example: import type { TripInput, Employee } from '@/types/database-helpers'
 *
 * Why this exists:
 * - database.ts is auto-generated by `npm run db:types` and gets overwritten
 * - These aliases would be lost on each regeneration
 * - This file provides a stable import source
 */

import type { Database } from './database'

// ============================================================
// RE-EXPORT GENERATED TYPES
// ============================================================

export type { Database, Json } from './database'

// Table type shortcuts
export type Tables = Database['public']['Tables']
export type Views = Database['public']['Views']
export type Functions = Database['public']['Functions']

// ============================================================
// TABLE ROW TYPES (for reading data)
// ============================================================

export type Company = Tables['companies']['Row']
export type Profile = Tables['profiles']['Row']
export type Employee = Tables['employees']['Row']
export type Trip = Tables['trips']['Row']
export type Alert = Tables['alerts']['Row']
export type AuditLog = Tables['audit_log']['Row']
export type SchengenCountry = Tables['schengen_countries']['Row']
export type ImportSession = Tables['import_sessions']['Row']
export type Tier = Tables['tiers']['Row']
export type BackgroundJob = Tables['background_jobs']['Row']
export type NotificationLog = Tables['notification_log']['Row']

// Settings tables
export type CompanySettings = Tables['company_settings']['Row']
export type NotificationPreferences = Tables['notification_preferences']['Row']
export type CompanyEntitlements = Tables['company_entitlements']['Row']
export type FeedbackSubmission = Tables['feedback_submissions']['Row']

// Admin tables
export type AdminAuditLog = Tables['admin_audit_log']['Row']
export type CompanyNotes = Tables['company_notes']['Row']
export type MfaBackupCode = Tables['mfa_backup_codes']['Row']
export type MfaBackupSession = Tables['mfa_backup_sessions']['Row']

// Compliance tables
export type EmployeeComplianceSnapshot = Tables['employee_compliance_snapshots']['Row']

// ============================================================
// TABLE INSERT TYPES (for creating records)
// ============================================================

export type CompanyInput = Tables['companies']['Insert']
export type ProfileInput = Tables['profiles']['Insert']
export type EmployeeInput = Tables['employees']['Insert']
export type TripInput = Tables['trips']['Insert']
export type AlertInput = Tables['alerts']['Insert']
export type AuditLogInput = Tables['audit_log']['Insert']
export type ImportSessionInput = Tables['import_sessions']['Insert']
export type TierInput = Tables['tiers']['Insert']
export type BackgroundJobInput = Tables['background_jobs']['Insert']
export type NotificationLogInput = Tables['notification_log']['Insert']

// Settings insert types
export type CompanySettingsInput = Tables['company_settings']['Insert']
export type NotificationPreferencesInput = Tables['notification_preferences']['Insert']
export type CompanyEntitlementsInput = Tables['company_entitlements']['Insert']
export type FeedbackSubmissionInput = Tables['feedback_submissions']['Insert']

// Admin insert types
export type AdminAuditLogInput = Tables['admin_audit_log']['Insert']
export type CompanyNotesInput = Tables['company_notes']['Insert']
export type MfaBackupCodeInput = Tables['mfa_backup_codes']['Insert']
export type MfaBackupSessionInput = Tables['mfa_backup_sessions']['Insert']

// Compliance insert types
export type EmployeeComplianceSnapshotInput = Tables['employee_compliance_snapshots']['Insert']

// Aliases for backward compatibility (Insert = Input naming)
export type TripInsert = TripInput
export type AlertInsert = AlertInput
export type NotificationLogInsert = NotificationLogInput
export type EmployeeInsert = EmployeeInput
export type ProfileInsert = ProfileInput
export type CompanyInsert = CompanyInput

// ============================================================
// TABLE UPDATE TYPES (for updating records)
// ============================================================

export type CompanyUpdate = Tables['companies']['Update']
export type ProfileUpdate = Tables['profiles']['Update']
export type EmployeeUpdate = Tables['employees']['Update']
export type TripUpdate = Tables['trips']['Update']
export type AlertUpdate = Tables['alerts']['Update']
export type AuditLogUpdate = Tables['audit_log']['Update']
export type ImportSessionUpdate = Tables['import_sessions']['Update']
export type TierUpdate = Tables['tiers']['Update']
export type BackgroundJobUpdate = Tables['background_jobs']['Update']
export type NotificationLogUpdate = Tables['notification_log']['Update']

// Settings update types
export type CompanySettingsUpdate = Tables['company_settings']['Update']
export type NotificationPreferencesUpdate = Tables['notification_preferences']['Update']
export type CompanyEntitlementsUpdate = Tables['company_entitlements']['Update']
export type FeedbackSubmissionUpdate = Tables['feedback_submissions']['Update']

// Admin update types
export type AdminAuditLogUpdate = Tables['admin_audit_log']['Update']
export type CompanyNotesUpdate = Tables['company_notes']['Update']
export type MfaBackupCodeUpdate = Tables['mfa_backup_codes']['Update']
export type MfaBackupSessionUpdate = Tables['mfa_backup_sessions']['Update']

// Compliance update types
export type EmployeeComplianceSnapshotUpdate = Tables['employee_compliance_snapshots']['Update']

// ============================================================
// VIEW TYPES
// ============================================================

export type EmployeeComplianceSummary = Views['employee_compliance_summary']['Row']

// ============================================================
// CUSTOM STRING LITERAL TYPES
// ============================================================

/**
 * Alert type - used to categorize different compliance alerts
 */
export type AlertType = 'warning' | 'urgent' | 'breach'

/**
 * Alert risk level - used to indicate severity
 * Values match the color-coded risk levels used in the UI
 */
export type AlertRiskLevel = 'green' | 'amber' | 'red'

// ============================================================
// COMPOSITE / JOINED TYPES
// ============================================================

/**
 * Alert with the associated employee data
 * Used when displaying alerts in the UI
 */
export type AlertWithEmployee = Alert & {
  employee?: Employee | null
}

/**
 * Employee with their trips
 * Used for compliance calculations
 */
export type EmployeeWithTrips = Employee & {
  trips: Trip[]
}

/**
 * Trip with employee details
 * Used in trip list views
 */
export type TripWithEmployee = Trip & {
  employee: Employee
}

/**
 * Profile with company details
 * Used for user context
 * Note: Supabase returns the relation as 'companies' (table name)
 */
export type ProfileWithCompany = Profile & {
  companies: Company | null
}

/**
 * Company with entitlements
 * Used for feature access checks
 */
export type CompanyWithEntitlements = Company & {
  company_entitlements: CompanyEntitlements | null
}

// ============================================================
// SERVER ACTION INPUT TYPES
// These types are used by server actions where company_id
// is added automatically from the authenticated user's profile
// ============================================================

/**
 * Trip create input for server actions
 * company_id is added server-side from authenticated user
 */
export type TripCreateInput = Omit<TripInput, 'company_id'>

/**
 * Employee create input for server actions
 * company_id is added server-side from authenticated user
 */
export type EmployeeCreateInput = Omit<EmployeeInput, 'company_id'>

/**
 * Bulk trip input for batch operations
 * company_id is added server-side from authenticated user
 */
export type BulkTripInput = Omit<TripInput, 'company_id' | 'id' | 'created_at' | 'updated_at' | 'travel_days'>

// ============================================================
// HELPER TYPES FOR FORMS
// ============================================================

/**
 * Trip form data (before submission)
 * Excludes auto-generated fields
 */
export type TripFormData = Omit<TripInput, 'id' | 'company_id' | 'created_at' | 'updated_at' | 'travel_days'>

/**
 * Employee form data (before submission)
 * Excludes auto-generated fields
 */
export type EmployeeFormData = Omit<EmployeeInput, 'id' | 'company_id' | 'created_at' | 'updated_at'>

// ============================================================
// TYPE GUARDS
// ============================================================

/**
 * Check if a profile has admin role
 */
export function isAdmin(profile: Profile): boolean {
  return profile.role === 'admin'
}

/**
 * Check if a profile has owner role
 */
export function isOwner(profile: Profile): boolean {
  return profile.role === 'owner'
}

/**
 * Check if a profile has owner or admin role
 */
export function isOwnerOrAdmin(profile: Profile): boolean {
  return profile.role === 'owner' || profile.role === 'admin'
}

/**
 * Check if a profile is a superadmin
 */
export function isSuperAdmin(profile: Profile): boolean {
  return profile.is_superadmin === true
}

/**
 * Check if a trip is in a Schengen country
 * Note: Actual validation should use the schengen_countries table
 */
export function isSchengenTrip(trip: Trip, schengenCodes: string[]): boolean {
  return schengenCodes.includes(trip.country)
}
